### PR TITLE
For monero version 0.14.0.0

### PR DESCRIPTION
**Pull request by moneroexamples**
New features and changes in preparation for monero v0.14.0.0.

Some new features are:

 - completely refactored access to blockchain (now using thread pool).
 - integrated xmregcore for decoding transactions
 - improved integration with mymonero-app-js
 - numerous bug and small improvements.

### CODE REVIEW

**Comment by TheTrunk** [comment]
Hello,
I am having issues while trying to build devel branch with monero master. Ubuntu 18.04
First is with 
```
git clone --recursive -b devel  https://github.com/moneroexamples/openmonero.git
```
obtaining
```
error: Server does not allow request for unadvertised object 939885dca443d994c0fc236ee7f292b6b11560c4
Fetched in submodule path 'src/xmregcore', but it did not contain 939885dca443d994c0fc236ee7f292b6b11560c4. Direct fetching of that commit failed.
```
Second issue is while running `cmake ..` command obtaining
```
-- Detecting CXX compile features - done
-- MONERO_DIR: ~/monero
CMake Error at CMakeLists.txt:42 (include):
  include could not find load file:

    MyUtils


-- Could NOT find MYSQL (missing: REQUIRED_VARS VERSION_VAR MYSQL_VERSION_STRING)
CMake Error at CMakeLists.txt:87 (create_git_version):
  Unknown CMake command "create_git_version".


-- Configuring incomplete, errors occurred!
See also "/mnt/volume_xmr/openmonero/build/CMakeFiles/CMakeOutput.log".
```

I see that there is `include(MyUtils)` in CMakeLists.txt but `cmake/MyUtils.cmake` was deleted so this first warning is resolved. However I was unable to resolve the MySQL error. Master branch does not give this error. Running `whereis mysql` returns
```
mysql: /usr/bin/mysql /usr/lib/mysql /etc/mysql /usr/include/mysql /usr/share/mysql /usr/share/man/man1/mysql.1.gz
```

**Comment by moneroexamples** [comment]
The problem with submodule `xmregcore` should be fixed. I could replicate your issue on Arch Linux. I fixed that and checked also on u1804. So you can git clone openmonero again.

For mysql, did you install mysql++ library, i.e., `sudo apt install libmysql++-dev`?

**Comment by TheTrunk** [comment]
Awesome. Last commit has resolved those building issues. Thank you.
Yes I do have that mysql++ library nstalled. 
Now I am getting following error while running `make`
```
[ 46%] Built target restbed
Scanning dependencies of target myxrmcore
[ 48%] Building CXX object src/xmregcore/src/CMakeFiles/myxrmcore.dir/MicroCore.cpp.o
In file included from /mnt/volume_xmr/openmonero/src/xmregcore/src/MicroCore.h:8:0,
                 from /mnt/volume_xmr/openmonero/src/xmregcore/src/MicroCore.cpp:5:
/mnt/volume_xmr/openmonero/src/xmregcore/src/monero_headers.h:20:10: fatal error: version.h: No such file or directory
 #include "version.h"
          ^~~~~~~~~~~
compilation terminated.
src/xmregcore/src/CMakeFiles/myxrmcore.dir/build.make:62: recipe for target 'src/xmregcore/src/CMakeFiles/myxrmcore.dir/MicroCore.cpp.o' failed
make[2]: *** [src/xmregcore/src/CMakeFiles/myxrmcore.dir/MicroCore.cpp.o] Error 1
CMakeFiles/Makefile2:181: recipe for target 'src/xmregcore/src/CMakeFiles/myxrmcore.dir/all' failed
make[1]: *** [src/xmregcore/src/CMakeFiles/myxrmcore.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by moneroexamples** [comment]
I think the issue is inccorect compilation of monero.  For use in moneroexamples projects, monero must be compiled with `USE_SINGLE_BUILDDIR=1` flag. e.g., `USE_SINGLE_BUILDDIR=1 make`. Also devel branch of openmonero requires branch `release-v0.13` of monero.


Examples of how to compile monero with the flag and the branch are here: 
https://github.com/moneroexamples/monero-compilation/blob/master/README.md

**Comment by TheTrunk** [comment]
Thank you, build issues have been resolved. However right upon starting I am obtaining following error
```
2019-03-08 16:57:54,191 [I,OM,main.cpp:int main(int, const char**):98] OpenMonero is starting
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.302] type must be number, but is null
Aborted (core dumped)
```

**Comment by TheTrunk** [comment]
Managed to resolve it. I was using my old config.json file turned out that there are some new fields now. Sorry

**Pull request merged**
